// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlWROkn0HwrgOB-XDCDD-NzV-Btzmqrn0',
    appId: '1:597552882943:web:471298bacd2d9b98b358ca',
    messagingSenderId: '597552882943',
    projectId: 'abdullah-dev-4a964',
    authDomain: 'abdullah-dev-4a964.firebaseapp.com',
    storageBucket: 'abdullah-dev-4a964.appspot.com',
    measurementId: 'G-Z3M4GMHXBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAdsOJuxjiFxP9VOcKr_LCtJCmQ903Q5E',
    appId: '1:597552882943:android:a8e0295ec7c0da7eb358ca',
    messagingSenderId: '597552882943',
    projectId: 'abdullah-dev-4a964',
    storageBucket: 'abdullah-dev-4a964.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmI53zP5ShrtUxJSBL6a51_aHLBPpcU_c',
    appId: '1:597552882943:ios:075bc58e89881b46b358ca',
    messagingSenderId: '597552882943',
    projectId: 'abdullah-dev-4a964',
    storageBucket: 'abdullah-dev-4a964.appspot.com',
    iosClientId: '597552882943-bjrfvnomv2j7j40qhvg8s7i1m2c32kkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesDoor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmI53zP5ShrtUxJSBL6a51_aHLBPpcU_c',
    appId: '1:597552882943:ios:075bc58e89881b46b358ca',
    messagingSenderId: '597552882943',
    projectId: 'abdullah-dev-4a964',
    storageBucket: 'abdullah-dev-4a964.appspot.com',
    iosClientId: '597552882943-bjrfvnomv2j7j40qhvg8s7i1m2c32kkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesDoor',
  );
}
